<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <PropertyGroup>
        <ModuleVersion>1.4.0</ModuleVersion>
        <DefineConstants/>
        <OutputBuildRoot>$(SolutionDir)build\</OutputBuildRoot>
        <OutputConfigRoot>$(OutputBuildRoot)$(Configuration)\</OutputConfigRoot>
        <OutputModuleRoot>$(OutputConfigRoot)$(AssemblyName)\</OutputModuleRoot>
    </PropertyGroup>

    <!-- Required to trick IDE into setting the configs -->
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' "/>
    
    <PropertyGroup Condition="$(Configuration.StartsWith('Debug'))">
        <OutputPackageRoot>$(SolutionDir)deploy\debug\</OutputPackageRoot>
        <Optimize>false</Optimize>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
        <XamlDebuggingInformation>True</XamlDebuggingInformation>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.StartsWith('Release'))">
        <OutputPackageRoot>$(SolutionDir)deploy\release\</OutputPackageRoot>
        <Optimize>true</Optimize>
        <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
        <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    <PropertyGroup Condition="!$(Configuration.EndsWith('1.3.15'))">
        <GameVersion>1.4.7</GameVersion>
        <BANNERLORD_GAME_DIR>$(BANNERLORD_GAME_DIR)</BANNERLORD_GAME_DIR>
        <BANNERLORD_GAME_DIR Condition=" '$(BANNERLORD_GAME_DIR)' == '' ">F:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord</BANNERLORD_GAME_DIR>
        <GameModulesDir>$(BANNERLORD_GAME_DIR)\Modules</GameModulesDir>
        <DefineConstants>$(DefineConstants);BL_1_4_7</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.EndsWith('1.3.15'))">
        <GameVersion>1.3.15</GameVersion>
        <BANNERLORD_GAME_DIR>F:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord V1-3-15</BANNERLORD_GAME_DIR>
        <GameModulesDir>F:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord V1-3-15\Modules</GameModulesDir>
        <DefineConstants>$(DefineConstants);BL_1_3_15</DefineConstants>
    </PropertyGroup>
    
    <PropertyGroup>
        <DeployDir>$(GameModulesDir)\$(AssemblyName)\</DeployDir>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.StartsWith('Debug'))">
        <PackageName>BLT-v$(ModuleVersion)-For-Game-Version-v$(GameVersion)-Debug.7z</PackageName>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.StartsWith('Release'))">
        <PackageName>BLT-v$(ModuleVersion)-For-Game-Version-v$(GameVersion).7z</PackageName>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageFullPath>$(OutputPackageRoot)$(PackageName)</PackageFullPath>
    </PropertyGroup>

    <PropertyGroup>
        <DebugType>full</DebugType>
        <PlatformTarget>x64</PlatformTarget>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugSymbols>true</DebugSymbols>
        <OutputPath>$(OutputModuleRoot)bin\Win64_Shipping_Client\</OutputPath>
        <EnableUnmanagedDebugging>true</EnableUnmanagedDebugging>
        <NoWarn>MSB3246;MSB3247;MSB3277;CS0649;CS0067</NoWarn>
        <XamlDebuggingInformation>True</XamlDebuggingInformation>
    </PropertyGroup>
</Project>
